### PR TITLE
Temporarily remove token processing that generates errorneous results

### PR DESCRIPTION
**Pull request by xuhdev**
introduced in e740f09b0549151fce19d13f5f00e6e58d52ccb7

Relevant comment: https://github.com/CODAIT/text-extensions-for-pandas/issues/148#issuecomment-730224771

### CODE REVIEW

**Comment by BryanCutler** [comment]
@xuhdev this is the cause of https://github.com/CODAIT/text-extensions-for-pandas/issues/148#issuecomment-730224771?

**Comment by xuhdev** [comment]
@BryanCutler Yes

**Comment by frreiss** [comment]
Maybe I'm missing something here. If this change goes through, won't the `download_and_correct_corpus.py` script generate an version of the corrected corpus with zero token corrections applied?

**Comment by xuhdev** [comment]
@frreiss We had token corrections manually applied, I believe. @kmh4321 

Eventually we have to figure out what went wrong in the token corrections code.

**Comment by frreiss** [comment]
@xuhdev if we were to switch to applying token corrections manually, we would need to provide users with detailed instructions on how to apply token corrections manually. I don't think users would appreciate that.

We need to fix the bug in the automated correction code.

**Comment by xuhdev** [comment]
Closed in favor of the real fix #33

**Pull request closed without merging**
