### PR TITLE
Add missing EOLs in token corrections, and some corrections to the token correction file

### PR DESCRIPTION
**Pull request by xuhdev**
When token corrections were first added in e740f09b0549151fce19d13f5f00e6e58d52ccb7, the EOLs were not written to the output file.

Relevant comment:
https://github.com/CODAIT/text-extensions-for-pandas/issues/148#issuecomment-730224771

### CODE REVIEW

**Comment by stefan-it** [comment]
Thanks for that fix! This fixes a lot of label errors :hugs: 

At the moment I could spot only a few errors in the dataset splits:

Training dataset: (first numer is line number):

```
65620 1997CD I-NP O
65621  -- : O O
```

Test dataset:

```
1133 - : OI-MISC
6542 X  IN I-PP O
6543 - : 0 0
6639 YNNP I-NP O
16322 NewmontNNP I-NP I-ORG
26725 Iowa I-NP I-LOC
42408 -: O O
```

**Comment by xuhdev** [comment]
@stefan-it Thanks for catching those errors! I've fixed those in the token correction files. Could you try again?

**Comment by stefan-it** [comment]
No problem,

for training dataset:

```
65620 1997CD I-NP O
```

and test dataset:

```
1133 - : OI-MISC
6542 X  IN I-PP O
6639 YNNP I-NP O
16322 NewmontNNP I-NP I-ORG
26725 Iowa I-NP I-LOC
42408 -: O O
```

:hugs:

**Comment by xuhdev** [comment]
Changes to the JSON file output by [json-diff](https://www.npmjs.com/package/json-diff):

```diff {
   correct_line: {
-    1131: "SKIING NNP I-NP I-MISC\n- : OI-MISC\nWORLD NNP I-NP I-MISC"
+    1131: "SKIING NNP I-NP I-MISC\n- : O I-MISC\nWORLD NNP I-NP I-MISC"
-    6545: "X  IN I-PP O\n- : 0 0\nDENVER NNP I-NP I-MISC"
+    6545: "X  IN I-PP O\n- : 0 O\nDENVER NNP I-NP I-MISC"
-    6640: "YNNP I-NP O\n- : O O \nGREEN NNP I-NP I-MISC"
+    6640: "Y NNP I-NP O\n- : O O \nGREEN NNP I-NP I-MISC"
-    16319: "NewmontNNP I-NP I-ORG\n- : O O\nSanta NNP I-NP I-ORG"
+    16319: "Newmont NNP I-NP I-ORG\n- : O O\nSanta NNP I-NP I-ORG"
-    26720: "Iowa I-NP I-LOC\n- : O O\nS NNP I-NP I-LOC"
+    26720: "Iowa NNP I-NP I-LOC\n- : O O\nS NNP I-NP I-LOC"
-    42385: "SKIING NNP I-NP O\n-: O O\nWORLD NNP I-NP I-MISC"
+    42385: "SKIING NNP I-NP O\n- : O O\nWORLD NNP I-NP I-MISC"
-    65636: "1997CD I-NP O\n -- : O O\nRuehe CD I-NP I-MISC"
+    65636: "1997 CD I-NP O\n-- : O O\nRuehe CD I-NP I-MISC"
   }
 }

```

**Comment by stefan-it** [comment]
Really cool :+1: almost all errors are gone now, only one minor issue with:

```
X  IN I-PP O
```

There's a leading space after `X` :)

**Comment by xuhdev** [comment]
Nice catch! Now the diff looks like this:

```diff
 {
   correct_span: {
-    14467: "[26, 39): 'Conservatives'  "
+    14467: "[26, 39): 'Conservatives'"
-    28718: "[11, 15): 'Iowa'  "
+    28718: "[11, 15): 'Iowa'"
   }
   correct_line: {
-    1131: "SKIING NNP I-NP I-MISC\n- : OI-MISC\nWORLD NNP I-NP I-MISC"
+    1131: "SKIING NNP I-NP I-MISC\n- : O I-MISC\nWORLD NNP I-NP I-MISC"
-    6545: "X  IN I-PP O\n- : 0 0\nDENVER NNP I-NP I-MISC"
+    6545: "X IN I-PP O\n- : 0 O\nDENVER NNP I-NP I-MISC"
-    6640: "YNNP I-NP O\n- : O O \nGREEN NNP I-NP I-MISC"
+    6640: "Y NNP I-NP O\n- : O O \nGREEN NNP I-NP I-MISC"
-    16319: "NewmontNNP I-NP I-ORG\n- : O O\nSanta NNP I-NP I-ORG"
+    16319: "Newmont NNP I-NP I-ORG\n- : O O\nSanta NNP I-NP I-ORG"
-    26720: "Iowa I-NP I-LOC\n- : O O\nS NNP I-NP I-LOC"
+    26720: "Iowa NNP I-NP I-LOC\n- : O O\nS NNP I-NP I-LOC"
-    42385: "SKIING NNP I-NP O\n-: O O\nWORLD NNP I-NP I-MISC"
+    42385: "SKIING NNP I-NP O\n- : O O\nWORLD NNP I-NP I-MISC"
-    65636: "1997CD I-NP O\n -- : O O\nRuehe CD I-NP I-MISC"
+    65636: "1997 CD I-NP O\n-- : O O\nRuehe CD I-NP I-MISC"
   }
 }
```

flair can parse through the generated dataset files now.

**Comment by frreiss** [comment]
These changes are looking pretty good now.

One remaining issue: The file `token_corrections.json` isn't meant to be edited by hand. The Juypter notebook `Hand_Token_Relabeler.ipynb` generates that file based off the contents of `corrected_labels/token_edits.csv`. We need to make the necessary changes to `token_edits.csv` and `Hand_Token_Relabeler.ipynb` such that the notebook will generate the current JSON file if it is run again.

We should also change the format of that JSON file from single-line to multi-line JSON. The way to make that change is to add `lines=True` to the call to `DataFrame.to_json()` in the last cell of `Hand_Token_Relabeler.ipynb`.

**Comment by frreiss** [comment]
Upon further inspection, it looks like `token_edits.csv` is the output of `token_correction_preprocessing.ipynb`, and there are issues in `token_edits.csv` caused by data entry errors in the audited label files. I am fixing some additional errors and will attach those fixes to #36. After that, I'll have a look at `Hand_Token_Relabeler.ipynb` again and see if we can't get the generation of a correct `token_corrections.json` more automated.

**Pull request merged**
